// types/plano-carreira/soft-skills.ts
import { z } from "zod";

export const HardSkillsEconoSchema = z.object({
    colaborador_id: z.string().uuid(),
    evaluator_id: z.string().uuid(),
    modelagem_financeira: z.string(),
    analise_de_investimentos: z.string(),
    avaliacao_de_ativos_de_infraestrutura: z.string(),
    microssimulacao_de_transporte: z.string(),
    macrossimulacao_de_transporte: z.string(),
    microssimulacao_industrial: z.string(),
    macrossimulacao_industrial: z.string(),
    regulacao_economica_e_tarifaria: z.string(),
    analise_de_riscos: z.string(),
    previsao_de_demanda: z.string(),
    analise_de_eficiencia_operacional: z.string(),
    excel_avancado_e_alternativas_open_source: z.string(),
    programacao_em_python: z.string(),
    programacao_em_r: z.string(),
    big_data_e_processamento_de_dados: z.string(),
    gis_e_geoprocessamento: z.string(),
    machine_learning_aplicado_a_transporte_e_economia: z.string(),
    automacao_de_processos_e_analise_de_dados: z.string(),
    simulacao_de_monte_carlo: z.string(),
    modelagem_de_equilibrio_geral: z.string(),
    modelagem_de_equilibrio_parcial: z.string(),
    desenvolvimento_de_apis_e_integracoes_de_dados: z.string(),
    banco_de_dados_e_sql: z.string(),
    conhecimento_do_setor_de_transportes: z.string(),
    conhecimento_do_setor_portuario_e_hidroviario: z.string(),
    conhecimento_do_setor_aeroportuario: z.string(),
    conhecimento_do_setor_ferroviario: z.string(),
    conhecimento_do_setor_rodoviario: z.string(),
    capacidade_de_elaboracao_de_relatorios_tecnicos: z.string(),
    capacidade_de_elaboracao_de_apresentacoes: z.string(),
    conhecimento_sobre_operacoes_de_comercio_exterior: z.string(),
    modelagem_de_processos: z.string(),
    gestao_de_objetivos_indicadores_e_metas: z.string(),
    gestao_da_qualidade_e_processos_de_auditoria: z.string(),
    modelagem_financeira_meta: z.string(),
    analise_de_investimentos_meta: z.string(),
    avaliacao_de_ativos_de_infraestrutura_meta: z.string(),
    microssimulacao_de_transporte_meta: z.string(),
    macrossimulacao_de_transporte_meta: z.string(),
    microssimulacao_industrial_meta: z.string(),
    macrossimulacao_industrial_meta: z.string(),
    regulacao_economica_e_tarifaria_meta: z.string(),
    analise_de_riscos_meta: z.string(),
    previsao_de_demanda_meta: z.string(),
    analise_de_eficiencia_operacional_meta: z.string(),
    excel_avancado_e_alternativas_open_source_meta: z.string(),
    programacao_em_python_meta: z.string(),
    programacao_em_r_meta: z.string(),
    big_data_e_processamento_de_dados_meta: z.string(),
    gis_e_geoprocessamento_meta: z.string(),
    machine_learning_aplicado_a_transporte_e_economia_meta: z.string(),
    automacao_de_processos_e_analise_de_dados_meta: z.string(),
    simulacao_de_monte_carlo_meta: z.string(),
    modelagem_de_equilibrio_geral_meta: z.string(),
    modelagem_de_equilibrio_parcial_meta: z.string(),
    desenvolvimento_de_apis_e_integracoes_de_dados_meta: z.string(),
    banco_de_dados_e_sql_meta: z.string(),
    conhecimento_do_setor_de_transportes_meta: z.string(),
    conhecimento_do_setor_portuario_e_hidroviario_meta: z.string(),
    conhecimento_do_setor_aeroportuario_meta: z.string(),
    conhecimento_do_setor_ferroviario_meta: z.string(),
    conhecimento_do_setor_rodoviario_meta: z.string(),
    capacidade_de_elaboracao_de_relatorios_tecnicos_meta: z.string(),
    capacidade_de_elaboracao_de_apresentacoes_meta: z.string(),
    conhecimento_sobre_operacoes_de_comercio_exterior_meta: z.string(),
    modelagem_de_processos_meta: z.string(),
    gestao_de_objetivos_indicadores_e_metas_meta: z.string(),
    gestao_da_qualidade_e_processos_de_auditoria_meta: z.string(),

});

export type HardSkillsEconoType = z.infer<typeof HardSkillsEconoSchema>;


export const HardSkillsMeioAmbienteSchema = z.object({
    colaborador_id: z.string().uuid(),
    evaluator_id: z.string().uuid(),
    dominio_de_qgis: z.string(),
    conhecimento_em_sig: z.string(),
    elaboracao_de_estudos_ambientais: z.string(),
    hidrologia_e_hidrogeologia: z.string(),
    simulacoes_hidrologicas_e_de_sedimentos: z.string(),
    analise_de_dados_ambientais: z.string(),
    sensoriamento_remoto: z.string(),
    estudos_de_viabilidade_ambiental: z.string(),
    legislacao_ambiental: z.string(),
    tecnica_de_campo: z.string(),
    simulacoes_hidrodinamicas_e_de_sedimentos_lado_mar: z.string(),
    gestao_de_bancos_de_dados: z.string(),
    conhecimento_em_geoprocessamento: z.string(),
    elaboracao_de_relatorios_tecnicos: z.string(),
    conhecimento_em_ecologia_e_biologia: z.string(),
    uso_de_drones_para_mapeamento: z.string(),
    conhecimento_em_geologia_e_geotecnia: z.string(),
    ferramentas_de_visualizacao_de_dados: z.string(),
    conhecimento_em_mudancas_climaticas: z.string(),
    gestao_de_projetos_ambientais: z.string(),
    economia_ambiental: z.string(),
    dominio_de_ferramentas_de_cad: z.string(),
    conhecimento_em_energias_renovaveis: z.string(),
    habilidades_em_redacao_cientifica: z.string(),
    conhecimento_em_gestao_de_riscos_ambientais: z.string(),
    dominio_de_qgis_meta: z.string(),
    conhecimento_em_sig_meta: z.string(),
    elaboracao_de_estudos_ambientais_meta: z.string(),
    hidrologia_e_hidrogeologia_meta: z.string(),
    simulacoes_hidrologicas_e_de_sedimentos_meta: z.string(),
    analise_de_dados_ambientais_meta: z.string(),
    sensoriamento_remoto_meta: z.string(),
    estudos_de_viabilidade_ambiental_meta: z.string(),
    legislacao_ambiental_meta: z.string(),
    tecnica_de_campo_meta: z.string(),
    simulacoes_hidrodinamicas_e_de_sedimentos_lado_mar_meta: z.string(),
    gestao_de_bancos_de_dados_meta: z.string(),
    conhecimento_em_geoprocessamento_meta: z.string(),
    elaboracao_de_relatorios_tecnicos_meta: z.string(),
    conhecimento_em_ecologia_e_biologia_meta: z.string(),
    uso_de_drones_para_mapeamento_meta: z.string(),
    conhecimento_em_geologia_e_geotecnia_meta: z.string(),
    ferramentas_de_visualizacao_de_dados_meta: z.string(),
    conhecimento_em_mudancas_climaticas_meta: z.string(),
    gestao_de_projetos_ambientais_meta: z.string(),
    economia_ambiental_meta: z.string(),
    dominio_de_ferramentas_de_cad_meta: z.string(),
    conhecimento_em_energias_renovaveis_meta: z.string(),
    habilidades_em_redacao_cientifica_meta: z.string(),
    conhecimento_em_gestao_de_riscos_ambientais_meta: z.string(),
});

export type HardSkillsMeioAmbienteType = z.infer<typeof HardSkillsMeioAmbienteSchema>;
