// types/plano-carreira/soft-skills.ts
import { z } from "zod";

export const softSkillsAssessmentSchema = z.object({
    colaborador_id: z.string().uuid(),
    evaluator_id: z.string().uuid(),
    comunicacao: z.string(),
    comunicacao_meta: z.string(),
    comunicacao_comment: z.string(),
    trabalho_em_equipe: z.string(),
    trabalho_em_equipe_meta: z.string(),
    trabalho_em_equipe_comment: z.string(),
    proatividade: z.string(),
    proatividade_meta: z.string(),
    proatividade_comment: z.string(),
    resolucao_de_problemas: z.string(),
    resolucao_de_problemas_meta: z.string(),
    resolucao_de_problemas_comment: z.string(),
    organizacao_de_tempo: z.string(),
    organizacao_de_tempo_meta: z.string(),
    organizacao_de_tempo_comment: z.string(),
    pensamento_critico: z.string(),
    pensamento_critico_meta: z.string(),
    pensamento_critico_comment: z.string(),
    capricho: z.string(),
    capricho_meta: z.string(),
    capricho_comment: z.string(),
    encarar_desafios: z.string(),
    encarar_desafios_meta: z.string(),
    encarar_desafios_comment: z.string(),
    postura_profissional: z.string(),
    postura_profissional_meta: z.string(),
    postura_profissional_comment: z.string(),
    gentileza_e_educacao: z.string(),
    gentileza_e_educacao_meta: z.string(),
    gentileza_e_educacao_comment: z.string(),
    engajamento_missao_visao: z.string(),
    engajamento_missao_visao_meta: z.string(),
    engajamento_missao_visao_comment: z.string(),
    created_at: z.string().optional(),
});

export type SoftSkillsAssessmentType = z.infer<typeof softSkillsAssessmentSchema>;
