begin;

-- =========================================================
-- 1. DADOS COMPLEMENTARES DO PORTFÓLIO
-- Um registro por projeto.
-- Os dados básicos continuam vindo de public.projects.
-- =========================================================

create table public.project_portfolio (
    id bigint generated by default as identity primary key,

    project_id integer not null unique
        references public.projects(id)
        on delete cascade,

    executive_summary text,
    challenge text,
    solution text,
    results text,
    quantitative_results text,

    associated_investment numeric(18,2),
    capex numeric(18,2),

    currency character varying(3) not null default 'BRL',

    completion_date date,

    notes text,

    allow_external_export boolean not null default false,
    show_values_in_pdf boolean not null default false,

    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    constraint project_portfolio_currency_length
        check (char_length(currency) = 3),

    constraint project_portfolio_investment_nonnegative
        check (
            associated_investment is null
            or associated_investment >= 0
        ),

    constraint project_portfolio_capex_nonnegative
        check (
            capex is null
            or capex >= 0
        )
);


-- =========================================================
-- 2. CATÁLOGO DE RÓTULOS DO PORTFÓLIO
--
-- categoria:
-- assunto -> Simulação, Demanda, Mercado etc.
-- setor   -> Portuário, Rodoviário, Ferroviário etc.
--
-- Área NÃO entra aqui.
-- Área continuará vindo dos departamentos do projeto.
-- =========================================================

create table public.portfolio_tags (
    id bigint generated by default as identity primary key,

    name character varying(100) not null,

    category character varying(20) not null,

    active boolean not null default true,

    sort_order integer not null default 0,

    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),

    constraint portfolio_tags_category_check
        check (category in ('assunto', 'setor')),

    constraint portfolio_tags_name_category_unique
        unique (name, category)
);


-- =========================================================
-- 3. RELAÇÃO ENTRE PORTFÓLIO E RÓTULOS
-- Um projeto pode possuir vários rótulos.
-- Um rótulo pode aparecer em vários projetos.
-- =========================================================

create table public.project_portfolio_tags (
    portfolio_id bigint not null
        references public.project_portfolio(id)
        on delete cascade,

    tag_id bigint not null
        references public.portfolio_tags(id)
        on delete cascade,

    created_at timestamp with time zone not null default now(),

    primary key (portfolio_id, tag_id)
);


-- =========================================================
-- 4. ÍNDICES PARA OS FILTROS FUTUROS
-- =========================================================

create index idx_project_portfolio_completion_date
    on public.project_portfolio(completion_date);

create index idx_project_portfolio_associated_investment
    on public.project_portfolio(associated_investment);

create index idx_portfolio_tags_category
    on public.portfolio_tags(category);

create index idx_portfolio_tags_name
    on public.portfolio_tags(name);

create index idx_project_portfolio_tags_tag
    on public.project_portfolio_tags(tag_id);

commit;