-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activities (
  id integer NOT NULL DEFAULT nextval('activities_id_seq'::regclass),
  name character varying NOT NULL,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'ativo'::atividade_status,
  macroprocesso_id integer NOT NULL,
  processo_id integer NOT NULL,
  sub_processo_id integer,
  CONSTRAINT activities_pkey PRIMARY KEY (id),
  CONSTRAINT activities_macroprocesso_id_fkey FOREIGN KEY (macroprocesso_id) REFERENCES public.macroprocesso(id),
  CONSTRAINT activities_processo_id_fkey FOREIGN KEY (processo_id) REFERENCES public.processo(id),
  CONSTRAINT activities_sub_processo_id_fkey FOREIGN KEY (sub_processo_id) REFERENCES public.sub_processo(id)
);
CREATE TABLE public.calendar_events (
  id integer NOT NULL DEFAULT nextval('calendar_events_id_seq'::regclass),
  title character varying NOT NULL,
  event_date date NOT NULL,
  type character varying NOT NULL,
  description text,
  CONSTRAINT calendar_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cargos (
  id integer NOT NULL DEFAULT nextval('cargos_id_seq'::regclass),
  nome character varying NOT NULL UNIQUE,
  CONSTRAINT cargos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.departments (
  id integer NOT NULL DEFAULT nextval('departments_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.event_departments (
  event_id integer NOT NULL,
  department_id integer NOT NULL,
  CONSTRAINT event_departments_pkey PRIMARY KEY (event_id, department_id),
  CONSTRAINT event_departments_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.calendar_events(id),
  CONSTRAINT event_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.hardskills_econo (
  colaborador_id uuid NOT NULL,
  evaluator_id uuid NOT NULL,
  modelagem_financeira text,
  analise_de_investimentos text,
  avaliacao_de_ativos_de_infraestrutura text,
  microssimulacao_de_transporte text,
  macrossimulacao_de_transporte text,
  microssimulacao_industrial text,
  macrossimulacao_industrial text,
  regulacao_economica_e_tarifaria text,
  analise_de_riscos text,
  previsao_de_demanda text,
  analise_de_eficiencia_operacional text,
  excel_avancado_e_alternativas_open_source text,
  programacao_em_python text,
  programacao_em_r text,
  big_data_e_processamento_de_dados text,
  gis_e_geoprocessamento text,
  machine_learning_aplicado_a_transporte_e_economia text,
  automacao_de_processos_e_analise_de_dados text,
  simulacao_de_monte_carlo text,
  modelagem_de_equilibrio_geral text,
  modelagem_de_equilibrio_parcial text,
  desenvolvimento_de_apis_e_integracoes_de_dados text,
  banco_de_dados_e_sql text,
  conhecimento_do_setor_de_transportes text,
  conhecimento_do_setor_portuario_e_hidroviario text,
  conhecimento_do_setor_aeroportuario text,
  conhecimento_do_setor_ferroviario text,
  conhecimento_do_setor_rodoviario text,
  capacidade_de_elaboracao_de_relatorios_tecnicos text,
  capacidade_de_elaboracao_de_apresentacoes text,
  conhecimento_sobre_operacoes_de_comercio_exterior text,
  modelagem_de_processos text,
  gestao_de_objetivos_indicadores_e_metas text,
  gestao_da_qualidade_e_processos_de_auditoria text,
  habilidade_tecnica_meta text,
  modelagem_financeira_meta text,
  analise_de_investimentos_meta text,
  avaliacao_de_ativos_de_infraestrutura_meta text,
  microssimulacao_de_transporte_meta text,
  macrossimulacao_de_transporte_meta text,
  microssimulacao_industrial_meta text,
  macrossimulacao_industrial_meta text,
  regulacao_economica_e_tarifaria_meta text,
  analise_de_riscos_meta text,
  previsao_de_demanda_meta text,
  analise_de_eficiencia_operacional_meta text,
  excel_avancado_e_alternativas_open_source_meta text,
  programacao_em_python_meta text,
  programacao_em_r_meta text,
  big_data_e_processamento_de_dados_meta text,
  gis_e_geoprocessamento_meta text,
  machine_learning_aplicado_a_transporte_e_economia_meta text,
  automacao_de_processos_e_analise_de_dados_meta text,
  simulacao_de_monte_carlo_meta text,
  modelagem_de_equilibrio_geral_meta text,
  modelagem_de_equilibrio_parcial_meta text,
  desenvolvimento_de_apis_e_integracoes_de_dados_meta text,
  banco_de_dados_e_sql_meta text,
  conhecimento_do_setor_de_transportes_meta text,
  conhecimento_do_setor_portuario_e_hidroviario_meta text,
  conhecimento_do_setor_aeroportuario_meta text,
  conhecimento_do_setor_ferroviario_meta text,
  conhecimento_do_setor_rodoviario_meta text,
  capacidade_de_elaboracao_de_relatorios_tecnicos_meta text,
  capacidade_de_elaboracao_de_apresentacoes_meta text,
  conhecimento_sobre_operacoes_de_comercio_exterior_meta text,
  modelagem_de_processos_meta text,
  gestao_de_objetivos_indicadores_e_metas_meta text,
  gestao_da_qualidade_e_processos_de_auditoria_meta text,
  CONSTRAINT hardskills_econo_pkey PRIMARY KEY (colaborador_id, evaluator_id),
  CONSTRAINT fk_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.users(id),
  CONSTRAINT fk_evaluator FOREIGN KEY (evaluator_id) REFERENCES public.users(id)
);
CREATE TABLE public.hardskills_mg (
  colaborador_id uuid NOT NULL,
  evaluator_id uuid NOT NULL,
  dominio_de_qgis text,
  conhecimento_em_sig text,
  elaboracao_de_estudos_ambientais text,
  hidrologia_e_hidrogeologia text,
  simulacoes_hidrologicas_e_de_sedimentos text,
  analise_de_dados_ambientais text,
  sensoriamento_remoto text,
  estudos_de_viabilidade_ambiental text,
  legislacao_ambiental text,
  tecnica_de_campo text,
  simulacoes_hidrodinamicas_e_de_sedimentos_lado_mar text,
  gestao_de_bancos_de_dados text,
  conhecimento_em_geoprocessamento text,
  elaboracao_de_relatorios_tecnicos text,
  conhecimento_em_ecologia_e_biologia text,
  uso_de_drones_para_mapeamento text,
  conhecimento_em_geologia_e_geotecnia text,
  ferramentas_de_visualizacao_de_dados text,
  conhecimento_em_mudancas_climaticas text,
  gestao_de_projetos_ambientais text,
  economia_ambiental text,
  dominio_de_ferramentas_de_cad text,
  conhecimento_em_energias_renovaveis text,
  habilidades_em_redacao_cientifica text,
  conhecimento_em_gestao_de_riscos_ambientais text,
  dominio_de_qgis_meta text,
  conhecimento_em_sig_meta text,
  elaboracao_de_estudos_ambientais_meta text,
  hidrologia_e_hidrogeologia_meta text,
  simulacoes_hidrologicas_e_de_sedimentos_meta text,
  analise_de_dados_ambientais_meta text,
  sensoriamento_remoto_meta text,
  estudos_de_viabilidade_ambiental_meta text,
  legislacao_ambiental_meta text,
  tecnica_de_campo_meta text,
  simulacoes_hidrodinamicas_e_de_sedimentos_lado_mar_meta text,
  gestao_de_bancos_de_dados_meta text,
  conhecimento_em_geoprocessamento_meta text,
  elaboracao_de_relatorios_tecnicos_meta text,
  conhecimento_em_ecologia_e_biologia_meta text,
  uso_de_drones_para_mapeamento_meta text,
  conhecimento_em_geologia_e_geotecnia_meta text,
  ferramentas_de_visualizacao_de_dados_meta text,
  conhecimento_em_mudancas_climaticas_meta text,
  gestao_de_projetos_ambientais_meta text,
  economia_ambiental_meta text,
  dominio_de_ferramentas_de_cad_meta text,
  conhecimento_em_energias_renovaveis_meta text,
  habilidades_em_redacao_cientifica_meta text,
  conhecimento_em_gestao_de_riscos_ambientais_meta text,
  CONSTRAINT hardskills_mg_pkey PRIMARY KEY (colaborador_id, evaluator_id),
  CONSTRAINT fk_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.users(id),
  CONSTRAINT fk_evaluator FOREIGN KEY (evaluator_id) REFERENCES public.users(id)
);
CREATE TABLE public.inconsistencies (
  id integer NOT NULL DEFAULT nextval('inconsistencies_id_seq'::regclass),
  user_id uuid NOT NULL,
  inconsistency_date date NOT NULL,
  type character varying NOT NULL,
  justification text,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inconsistencies_pkey PRIMARY KEY (id),
  CONSTRAINT inconsistencies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.macroprocesso (
  id integer NOT NULL DEFAULT nextval('macroprocesso_id_seq'::regclass),
  nome text NOT NULL UNIQUE,
  status USER-DEFINED NOT NULL DEFAULT 'ativo'::atividade_status,
  CONSTRAINT macroprocesso_pkey PRIMARY KEY (id)
);
CREATE TABLE public.processo (
  id integer NOT NULL DEFAULT nextval('processo_id_seq'::regclass),
  nome text NOT NULL,
  macroprocesso_id integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ativo'::atividade_status,
  CONSTRAINT processo_pkey PRIMARY KEY (id),
  CONSTRAINT processo_macroprocesso_id_fkey FOREIGN KEY (macroprocesso_id) REFERENCES public.macroprocesso(id)
);
CREATE TABLE public.projects (
  id integer NOT NULL DEFAULT nextval('projects_id_seq'::regclass),
  name character varying NOT NULL,
  code character varying UNIQUE,
  estimated_hours integer,
  description text,
  department_id integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ativo'::projct_status,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.soft_skills_assessment (
  id integer NOT NULL DEFAULT nextval('soft_skills_assessment_id_seq'::regclass),
  colaborador_id uuid NOT NULL,
  evaluator_id uuid NOT NULL,
  comunicacao text NOT NULL,
  trabalho_em_equipe text NOT NULL,
  proatividade text NOT NULL,
  resolucao_de_problemas text NOT NULL,
  organizacao_de_tempo text NOT NULL,
  pensamento_critico text NOT NULL,
  capricho text NOT NULL,
  encarar_desafios text NOT NULL,
  postura_profissional text NOT NULL,
  gentileza_e_educacao text NOT NULL,
  engajamento_missao_visao text NOT NULL,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  comunicacao_meta text,
  trabalho_em_equipe_meta text,
  proatividade_meta text,
  resolucao_de_problemas_meta text,
  organizacao_de_tempo_meta text,
  pensamento_critico_meta text,
  capricho_meta text,
  encarar_desafios_meta text,
  postura_profissional_meta text,
  gentileza_e_educacao_meta text,
  engajamento_missao_visao_meta text,
  CONSTRAINT soft_skills_assessment_pkey PRIMARY KEY (id),
  CONSTRAINT fk_user FOREIGN KEY (colaborador_id) REFERENCES public.users(id),
  CONSTRAINT fk_evaluator FOREIGN KEY (evaluator_id) REFERENCES public.users(id),
  CONSTRAINT fk_softskills_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.users(id),
  CONSTRAINT fk_softskills_evaluator FOREIGN KEY (evaluator_id) REFERENCES public.users(id)
);
CREATE TABLE public.sub_processo (
  id integer NOT NULL DEFAULT nextval('sub_processo_id_seq'::regclass),
  nome text NOT NULL,
  processo_id integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ativo'::atividade_status,
  CONSTRAINT sub_processo_pkey PRIMARY KEY (id),
  CONSTRAINT sub_processo_processo_id_fkey FOREIGN KEY (processo_id) REFERENCES public.processo(id)
);
CREATE TABLE public.time_allocations (
  id integer NOT NULL DEFAULT nextval('time_allocations_id_seq'::regclass),
  user_id uuid NOT NULL,
  project_id integer NOT NULL,
  activity_id integer NOT NULL,
  allocation_date date NOT NULL,
  hours numeric NOT NULL,
  comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT time_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT time_allocations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT time_allocations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT time_allocations_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.activities(id)
);
CREATE TABLE public.time_entries (
  user_id uuid NOT NULL,
  entry_date date NOT NULL,
  period smallint NOT NULL CHECK (period = ANY (ARRAY[1, 2, 3])),
  entry_time time without time zone,
  exit_time time without time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT time_entries_pkey PRIMARY KEY (user_id, entry_date, period)
);
CREATE TABLE public.user_departments (
  user_id uuid NOT NULL,
  department_id integer NOT NULL,
  CONSTRAINT user_departments_pkey PRIMARY KEY (user_id, department_id),
  CONSTRAINT user_departments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  role USER-DEFINED NOT NULL DEFAULT 'COLABORADOR'::user_role,
  cargo_id integer,
  status character varying NOT NULL DEFAULT 'active'::character varying,
  working_hours_per_day integer NOT NULL DEFAULT 8,
  banco_horas_anterior numeric NOT NULL DEFAULT 0,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_cargo_id_fkey FOREIGN KEY (cargo_id) REFERENCES public.cargos(id)
);