-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activities (
  id integer NOT NULL DEFAULT nextval('activities_id_seq'::regclass),
  name character varying NOT NULL,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'ativo'::atividade_status,
  macroprocesso_id integer NOT NULL,
  processo_id integer NOT NULL,
  sub_processo_id integer,
  CONSTRAINT activities_pkey PRIMARY KEY (id),
  CONSTRAINT activities_macroprocesso_id_fkey FOREIGN KEY (macroprocesso_id) REFERENCES public.macroprocesso(id),
  CONSTRAINT activities_processo_id_fkey FOREIGN KEY (processo_id) REFERENCES public.processo(id),
  CONSTRAINT activities_sub_processo_id_fkey FOREIGN KEY (sub_processo_id) REFERENCES public.sub_processo(id)
);
CREATE TABLE public.calendar_events (
  id integer NOT NULL DEFAULT nextval('calendar_events_id_seq'::regclass),
  title character varying NOT NULL,
  event_date date NOT NULL,
  type character varying NOT NULL,
  description text,
  CONSTRAINT calendar_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cargos (
  id integer NOT NULL DEFAULT nextval('cargos_id_seq'::regclass),
  nome character varying NOT NULL UNIQUE,
  CONSTRAINT cargos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.comment_feedback (
  colaborador_id uuid NOT NULL,
  comment text,
  created_at date NOT NULL DEFAULT CURRENT_DATE,
  semestre USER-DEFINED,
  CONSTRAINT comment_feedback_pkey PRIMARY KEY (colaborador_id, created_at),
  CONSTRAINT fk_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.users(id)
);
CREATE TABLE public.departments (
  id integer NOT NULL DEFAULT nextval('departments_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  CONSTRAINT departments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.event_departments (
  event_id integer NOT NULL,
  department_id integer NOT NULL,
  CONSTRAINT event_departments_pkey PRIMARY KEY (event_id, department_id),
  CONSTRAINT event_departments_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.calendar_events(id),
  CONSTRAINT event_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.hardskills_econo (
  colaborador_id uuid NOT NULL,
  evaluator_id uuid NOT NULL,
  modelagem_financeira text,
  modelagem_financeira_meta text,
  modelagem_financeira_comment text,
  analise_de_investimentos text,
  analise_de_investimentos_meta text,
  analise_de_investimentos_comment text,
  avaliacao_de_ativos_de_infraestrutura text,
  avaliacao_de_ativos_de_infraestrutura_meta text,
  avaliacao_de_ativos_de_infraestrutura_comment text,
  microssimulacao_de_transporte text,
  microssimulacao_de_transporte_meta text,
  microssimulacao_de_transporte_comment text,
  macrossimulacao_de_transporte text,
  macrossimulacao_de_transporte_meta text,
  macrossimulacao_de_transporte_comment text,
  microssimulacao_industrial text,
  microssimulacao_industrial_meta text,
  microssimulacao_industrial_comment text,
  macrossimulacao_industrial text,
  macrossimulacao_industrial_meta text,
  macrossimulacao_industrial_comment text,
  regulacao_economica_e_tarifaria text,
  regulacao_economica_e_tarifaria_meta text,
  regulacao_economica_e_tarifaria_comment text,
  analise_de_riscos text,
  analise_de_riscos_meta text,
  analise_de_riscos_comment text,
  previsao_de_demanda text,
  previsao_de_demanda_meta text,
  previsao_de_demanda_comment text,
  analise_de_eficiencia_operacional text,
  analise_de_eficiencia_operacional_meta text,
  analise_de_eficiencia_operacional_comment text,
  excel_avancado_e_alternativas_open_source text,
  excel_avancado_e_alternativas_open_source_meta text,
  excel_avancado_e_alternativas_open_source_comment text,
  programacao_em_python text,
  programacao_em_python_meta text,
  programacao_em_python_comment text,
  programacao_em_r text,
  programacao_em_r_meta text,
  programacao_em_r_comment text,
  big_data_e_processamento_de_dados text,
  big_data_e_processamento_de_dados_meta text,
  big_data_e_processamento_de_dados_comment text,
  gis_e_geoprocessamento text,
  gis_e_geoprocessamento_meta text,
  gis_e_geoprocessamento_comment text,
  machine_learning_aplicado_a_transporte_e_economia text,
  machine_learning_aplicado_a_transporte_e_economia_meta text,
  machine_learning_aplicado_a_transporte_e_economia_comment text,
  automacao_de_processos_e_analise_de_dados text,
  automacao_de_processos_e_analise_de_dados_meta text,
  automacao_de_processos_e_analise_de_dados_comment text,
  simulacao_de_monte_carlo text,
  simulacao_de_monte_carlo_meta text,
  simulacao_de_monte_carlo_comment text,
  modelagem_de_equilibrio_geral text,
  modelagem_de_equilibrio_geral_meta text,
  modelagem_de_equilibrio_geral_comment text,
  modelagem_de_equilibrio_parcial text,
  modelagem_de_equilibrio_parcial_meta text,
  modelagem_de_equilibrio_parcial_comment text,
  desenvolvimento_de_apis_e_integracoes_de_dados text,
  desenvolvimento_de_apis_e_integracoes_de_dados_meta text,
  desenvolvimento_de_apis_e_integracoes_de_dados_comment text,
  banco_de_dados_e_sql text,
  banco_de_dados_e_sql_meta text,
  banco_de_dados_e_sql_comment text,
  conhecimento_do_setor_de_transportes text,
  conhecimento_do_setor_de_transportes_meta text,
  conhecimento_do_setor_de_transportes_comment text,
  conhecimento_do_setor_portuario_e_hidroviario text,
  conhecimento_do_setor_portuario_e_hidroviario_meta text,
  conhecimento_do_setor_portuario_e_hidroviario_comment text,
  conhecimento_do_setor_aeroportuario text,
  conhecimento_do_setor_aeroportuario_meta text,
  conhecimento_do_setor_aeroportuario_comment text,
  conhecimento_do_setor_ferroviario text,
  conhecimento_do_setor_ferroviario_meta text,
  conhecimento_do_setor_ferroviario_comment text,
  conhecimento_do_setor_rodoviario text,
  conhecimento_do_setor_rodoviario_meta text,
  conhecimento_do_setor_rodoviario_comment text,
  capacidade_de_elaboracao_de_relatorios_tecnicos text,
  capacidade_de_elaboracao_de_relatorios_tecnicos_meta text,
  capacidade_de_elaboracao_de_relatorios_tecnicos_comment text,
  capacidade_de_elaboracao_de_apresentacoes text,
  capacidade_de_elaboracao_de_apresentacoes_meta text,
  capacidade_de_elaboracao_de_apresentacoes_comment text,
  conhecimento_sobre_operacoes_de_comercio_exterior text,
  conhecimento_sobre_operacoes_de_comercio_exterior_meta text,
  conhecimento_sobre_operacoes_de_comercio_exterior_comment text,
  modelagem_de_processos text,
  modelagem_de_processos_meta text,
  modelagem_de_processos_comment text,
  gestao_de_objetivos_indicadores_e_metas text,
  gestao_de_objetivos_indicadores_e_metas_meta text,
  gestao_de_objetivos_indicadores_e_metas_comment text,
  gestao_da_qualidade_e_processos_de_auditoria text,
  gestao_da_qualidade_e_processos_de_auditoria_meta text,
  gestao_da_qualidade_e_processos_de_auditoria_comment text,
  created_at date DEFAULT CURRENT_DATE,
  semestre USER-DEFINED,
  CONSTRAINT hardskills_econo_pkey PRIMARY KEY (colaborador_id, evaluator_id),
  CONSTRAINT fk_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.users(id),
  CONSTRAINT fk_evaluator FOREIGN KEY (evaluator_id) REFERENCES public.users(id)
);
CREATE TABLE public.hardskills_financeiro (
  colaborador_id uuid NOT NULL,
  evaluator_id uuid NOT NULL,
  escrituracao_contabil_completa text,
  escrituracao_contabil_completa_meta text,
  escrituracao_contabil_completa_comment text,
  fechamento_contabil text,
  fechamento_contabil_meta text,
  fechamento_contabil_comment text,
  conciliacao_bancaria_contabil text,
  conciliacao_bancaria_contabil_meta text,
  conciliacao_bancaria_contabil_comment text,
  apuracao_impostos text,
  apuracao_impostos_meta text,
  apuracao_impostos_comment text,
  conformidade_fiscal_trabalhista text,
  conformidade_fiscal_trabalhista_meta text,
  conformidade_fiscal_trabalhista_comment text,
  gestao_fluxo_caixa text,
  gestao_fluxo_caixa_meta text,
  gestao_fluxo_caixa_comment text,
  elaboracao_analise_dre text,
  elaboracao_analise_dre_meta text,
  elaboracao_analise_dre_comment text,
  projecao_receitas_despesas text,
  projecao_receitas_despesas_meta text,
  projecao_receitas_despesas_comment text,
  gestao_contas_pagar_receber text,
  gestao_contas_pagar_receber_meta text,
  gestao_contas_pagar_receber_comment text,
  indicadores_financeiros text,
  indicadores_financeiros_meta text,
  indicadores_financeiros_comment text,
  valuation text,
  valuation_meta text,
  valuation_comment text,
  relacionamento_bancario text,
  relacionamento_bancario_meta text,
  relacionamento_bancario_comment text,
  planejamento_orcamentario text,
  planejamento_orcamentario_meta text,
  planejamento_orcamentario_comment text,
  analise_variacoes_orcamentarias text,
  analise_variacoes_orcamentarias_meta text,
  analise_variacoes_orcamentarias_comment text,
  compras_negociacao text,
  compras_negociacao_meta text,
  compras_negociacao_comment text,
  gestao_contratos text,
  gestao_contratos_meta text,
  gestao_contratos_comment text,
  folha_pagamento text,
  folha_pagamento_meta text,
  folha_pagamento_comment text,
  beneficios_trabalhistas text,
  beneficios_trabalhistas_meta text,
  beneficios_trabalhistas_comment text,
  admissao_demissao text,
  admissao_demissao_meta text,
  admissao_demissao_comment text,
  encargos_social_fiscal text,
  encargos_social_fiscal_meta text,
  encargos_social_fiscal_comment text,
  esocial text,
  esocial_meta text,
  esocial_comment text,
  erp_omie text,
  erp_omie_meta text,
  erp_omie_comment text,
  excel_avancado text,
  excel_avancado_meta text,
  excel_avancado_comment text,
  power_bi text,
  power_bi_meta text,
  power_bi_comment text,
  powerpoint text,
  powerpoint_meta text,
  powerpoint_comment text,
  canva text,
  canva_meta text,
  canva_comment text,
  teams text,
  teams_meta text,
  teams_comment text,
  controles_internos text,
  controles_internos_meta text,
  controles_internos_comment text,
  riscos_financeiros_operacionais text,
  riscos_financeiros_operacionais_meta text,
  riscos_financeiros_operacionais_comment text,
  auditorias_externas text,
  auditorias_externas_meta text,
  auditorias_externas_comment text,
  relacionamento_clientes_fornecedores text,
  relacionamento_clientes_fornecedores_meta text,
  relacionamento_clientes_fornecedores_comment text,
  auditorias_fiscalizacoes text,
  auditorias_fiscalizacoes_meta text,
  auditorias_fiscalizacoes_comment text,
  relatorios_financeiros text,
  relatorios_financeiros_meta text,
  relatorios_financeiros_comment text,
  created_at date DEFAULT CURRENT_DATE,
  semestre USER-DEFINED,
  CONSTRAINT hardskills_financeiro_pkey PRIMARY KEY (colaborador_id, evaluator_id),
  CONSTRAINT fk_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.users(id),
  CONSTRAINT fk_evaluator FOREIGN KEY (evaluator_id) REFERENCES public.users(id)
);
CREATE TABLE public.hardskills_mg (
  colaborador_id uuid NOT NULL,
  evaluator_id uuid NOT NULL,
  dominio_de_qgis text,
  dominio_de_qgis_meta text,
  dominio_de_qgis_comment text,
  conhecimento_em_sig text,
  conhecimento_em_sig_meta text,
  conhecimento_em_sig_comment text,
  elaboracao_de_estudos_ambientais text,
  elaboracao_de_estudos_ambientais_meta text,
  elaboracao_de_estudos_ambientais_comment text,
  hidrologia_e_hidrogeologia text,
  hidrologia_e_hidrogeologia_meta text,
  hidrologia_e_hidrogeologia_comment text,
  simulacoes_hidrologicas_e_de_sedimentos text,
  simulacoes_hidrologicas_e_de_sedimentos_meta text,
  simulacoes_hidrologicas_e_de_sedimentos_comment text,
  analise_de_dados_ambientais text,
  analise_de_dados_ambientais_meta text,
  analise_de_dados_ambientais_comment text,
  sensoriamento_remoto text,
  sensoriamento_remoto_meta text,
  sensoriamento_remoto_comment text,
  estudos_de_viabilidade_ambiental text,
  estudos_de_viabilidade_ambiental_meta text,
  estudos_de_viabilidade_ambiental_comment text,
  legislacao_ambiental text,
  legislacao_ambiental_meta text,
  legislacao_ambiental_comment text,
  tecnica_de_campo text,
  tecnica_de_campo_meta text,
  tecnica_de_campo_comment text,
  simulacoes_hidrodinamicas_e_de_sedimentos_lado_mar text,
  simulacoes_hidrodinamicas_e_de_sedimentos_lado_mar_meta text,
  simulacoes_hidrodinamicas_e_de_sedimentos_lado_mar_comment text,
  gestao_de_bancos_de_dados text,
  gestao_de_bancos_de_dados_meta text,
  gestao_de_bancos_de_dados_comment text,
  conhecimento_em_geoprocessamento text,
  conhecimento_em_geoprocessamento_meta text,
  conhecimento_em_geoprocessamento_comment text,
  elaboracao_de_relatorios_tecnicos text,
  elaboracao_de_relatorios_tecnicos_meta text,
  elaboracao_de_relatorios_tecnicos_comment text,
  conhecimento_em_ecologia_e_biologia text,
  conhecimento_em_ecologia_e_biologia_meta text,
  conhecimento_em_ecologia_e_biologia_comment text,
  uso_de_drones_para_mapeamento text,
  uso_de_drones_para_mapeamento_meta text,
  uso_de_drones_para_mapeamento_comment text,
  conhecimento_em_geologia_e_geotecnia text,
  conhecimento_em_geologia_e_geotecnia_meta text,
  conhecimento_em_geologia_e_geotecnia_comment text,
  ferramentas_de_visualizacao_de_dados text,
  ferramentas_de_visualizacao_de_dados_meta text,
  ferramentas_de_visualizacao_de_dados_comment text,
  conhecimento_em_mudancas_climaticas text,
  conhecimento_em_mudancas_climaticas_meta text,
  conhecimento_em_mudancas_climaticas_comment text,
  gestao_de_projetos_ambientais text,
  gestao_de_projetos_ambientais_meta text,
  gestao_de_projetos_ambientais_comment text,
  economia_ambiental text,
  economia_ambiental_meta text,
  economia_ambiental_comment text,
  dominio_de_ferramentas_de_cad text,
  dominio_de_ferramentas_de_cad_meta text,
  dominio_de_ferramentas_de_cad_comment text,
  conhecimento_em_energias_renovaveis text,
  conhecimento_em_energias_renovaveis_meta text,
  conhecimento_em_energias_renovaveis_comment text,
  habilidades_em_redacao_cientifica text,
  habilidades_em_redacao_cientifica_meta text,
  habilidades_em_redacao_cientifica_comment text,
  conhecimento_em_gestao_de_riscos_ambientais text,
  conhecimento_em_gestao_de_riscos_ambientais_meta text,
  conhecimento_em_gestao_de_riscos_ambientais_comment text,
  created_at date DEFAULT CURRENT_DATE,
  semestre USER-DEFINED,
  CONSTRAINT hardskills_mg_pkey PRIMARY KEY (colaborador_id, evaluator_id),
  CONSTRAINT fk_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.users(id),
  CONSTRAINT fk_evaluator FOREIGN KEY (evaluator_id) REFERENCES public.users(id)
);
CREATE TABLE public.hardskills_ti (
  colaborador_id uuid NOT NULL,
  evaluator_id uuid NOT NULL,
  programacao_em_python text,
  programacao_em_python_meta text,
  programacao_em_python_comment text,
  programacao_em_nodejs text,
  programacao_em_nodejs_meta text,
  programacao_em_nodejs_comment text,
  desenvolvimento_de_apis_restful text,
  desenvolvimento_de_apis_restful_meta text,
  desenvolvimento_de_apis_restful_comment text,
  desenvolvimento_de_microservicos text,
  desenvolvimento_de_microservicos_meta text,
  desenvolvimento_de_microservicos_comment text,
  consumo_de_apis_externas text,
  consumo_de_apis_externas_meta text,
  consumo_de_apis_externas_comment text,
  versionamento_de_codigo_git text,
  versionamento_de_codigo_git_meta text,
  versionamento_de_codigo_git_comment text,
  criacao_de_scripts_de_automacao text,
  criacao_de_scripts_de_automacao_meta text,
  criacao_de_scripts_de_automacao_comment text,
  html5_e_css3 text,
  html5_e_css3_meta text,
  html5_e_css3_comment text,
  javascript_avancado text,
  javascript_avancado_meta text,
  javascript_avancado_comment text,
  frameworks_js_react_angular_vue text,
  frameworks_js_react_angular_vue_meta text,
  frameworks_js_react_angular_vue_comment text,
  typescript text,
  typescript_meta text,
  typescript_comment text,
  criacao_de_spa text,
  criacao_de_spa_meta text,
  criacao_de_spa_comment text,
  responsividade_bootstrap_tailwind text,
  responsividade_bootstrap_tailwind_meta text,
  responsividade_bootstrap_tailwind_comment text,
  consumo_de_apis_no_frontend text,
  consumo_de_apis_no_frontend_meta text,
  consumo_de_apis_no_frontend_comment text,
  testes_unitarios_frontend_jest_mocha text,
  testes_unitarios_frontend_jest_mocha_meta text,
  testes_unitarios_frontend_jest_mocha_comment text,
  otimizacao_de_performance_web text,
  otimizacao_de_performance_web_meta text,
  otimizacao_de_performance_web_comment text,
  definicao_de_arquitetura_em_camadas text,
  definicao_de_arquitetura_em_camadas_meta text,
  definicao_de_arquitetura_em_camadas_comment text,
  arquitetura_orientada_a_servicos_soa text,
  arquitetura_orientada_a_servicos_soa_meta text,
  arquitetura_orientada_a_servicos_soa_comment text,
  modelagem_de_dominio_ddd text,
  modelagem_de_dominio_ddd_meta text,
  modelagem_de_dominio_ddd_comment text,
  implementacao_de_padroes_de_projeto_design_patterns text,
  implementacao_de_padroes_de_projeto_design_patterns_meta text,
  implementacao_de_padroes_de_projeto_design_patterns_comment text,
  arquitetura_de_microservicos text,
  arquitetura_de_microservicos_meta text,
  arquitetura_de_microservicos_comment text,
  modelagem_de_banco_relacional_postgresql_mysqlsqlserver text,
  modelagem_de_banco_relacional_postgresql_mysqlsqlserver_meta text,
  modelagem_de_banco_relacional_postgresql_mysqlsqlserver_comment text,
  modelagem_de_banco_nosql_mongodb_redis text,
  modelagem_de_banco_nosql_mongodb_redis_meta text,
  modelagem_de_banco_nosql_mongodb_redis_comment text,
  criacao_e_otimizacao_de_queries_sql text,
  criacao_e_otimizacao_de_queries_sql_meta text,
  criacao_e_otimizacao_de_queries_sql_comment text,
  procedures_triggers_e_functions text,
  procedures_triggers_e_functions_meta text,
  procedures_triggers_e_functions_comment text,
  backup_e_restore_de_bases text,
  backup_e_restore_de_bases_meta text,
  backup_e_restore_de_bases_comment text,
  criacao_e_gerenciamento_de_pipelines_cicd text,
  criacao_e_gerenciamento_de_pipelines_cicd_meta text,
  criacao_e_gerenciamento_de_pipelines_cicd_comment text,
  containerizacao_docker text,
  containerizacao_docker_meta text,
  containerizacao_docker_comment text,
  orquestracao_de_containers_kubernetes text,
  orquestracao_de_containers_kubernetes_meta text,
  orquestracao_de_containers_kubernetes_comment text,
  provisionamento_de_infraestrutura_terraform_ansible text,
  provisionamento_de_infraestrutura_terraform_ansible_meta text,
  provisionamento_de_infraestrutura_terraform_ansible_comment text,
  configuracao_de_ambientes_cloud_aws_azure_gcp text,
  configuracao_de_ambientes_cloud_aws_azure_gcp_meta text,
  configuracao_de_ambientes_cloud_aws_azure_gcp_comment text,
  monitoramento_de_aplicacoes_prometheus_grafana text,
  monitoramento_de_aplicacoes_prometheus_grafana_meta text,
  monitoramento_de_aplicacoes_prometheus_grafana_comment text,
  criacao_de_wireframes_e_prototipos_figma_adobe_xd text,
  criacao_de_wireframes_e_prototipos_figma_adobe_xd_meta text,
  criacao_de_wireframes_e_prototipos_figma_adobe_xd_comment text,
  usabilidade_e_design_centrado_no_usuario text,
  usabilidade_e_design_centrado_no_usuario_meta text,
  usabilidade_e_design_centrado_no_usuario_comment text,
  aplicacao_de_guidelines_de_design text,
  aplicacao_de_guidelines_de_design_meta text,
  aplicacao_de_guidelines_de_design_comment text,
  testes_unitarios_backend text,
  testes_unitarios_backend_meta text,
  testes_unitarios_backend_comment text,
  testes_automatizados_frontend text,
  testes_automatizados_frontend_meta text,
  testes_automatizados_frontend_comment text,
  testes_de_integracao text,
  testes_de_integracao_meta text,
  testes_de_integracao_comment text,
  testes_de_carga_e_performance text,
  testes_de_carga_e_performance_meta text,
  testes_de_carga_e_performance_comment text,
  cobertura_de_testes_e_relatorios text,
  cobertura_de_testes_e_relatorios_meta text,
  cobertura_de_testes_e_relatorios_comment text,
  microsoft_teams_comunicacao_e_colaboracao text,
  microsoft_teams_comunicacao_e_colaboracao_meta text,
  microsoft_teams_comunicacao_e_colaboracao_comment text,
  documentacao_tecnica_estruturada text,
  documentacao_tecnica_estruturada_meta text,
  documentacao_tecnica_estruturada_comment text,
  scrum text,
  scrum_meta text,
  scrum_comment text,
  kanban text,
  kanban_meta text,
  kanban_comment text,
  gestao_de_backlog text,
  gestao_de_backlog_meta text,
  gestao_de_backlog_comment text,
  sprint_planning_e_review text,
  sprint_planning_e_review_meta text,
  sprint_planning_e_review_comment text,
  praticas_de_secure_coding text,
  praticas_de_secure_coding_meta text,
  praticas_de_secure_coding_comment text,
  autenticacao_e_autorizacao_oauth2_jwt text,
  autenticacao_e_autorizacao_oauth2_jwt_meta text,
  autenticacao_e_autorizacao_oauth2_jwt_comment text,
  lgpd_aplicada_a_sistemas text,
  lgpd_aplicada_a_sistemas_meta text,
  lgpd_aplicada_a_sistemas_comment text,
  gestao_de_vulnerabilidades_e_correcoes text,
  gestao_de_vulnerabilidades_e_correcoes_meta text,
  gestao_de_vulnerabilidades_e_correcoes_comment text,
  created_at date DEFAULT CURRENT_DATE,
  semestre USER-DEFINED,
  CONSTRAINT hardskills_ti_pkey PRIMARY KEY (colaborador_id, evaluator_id),
  CONSTRAINT fk_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.users(id),
  CONSTRAINT fk_evaluator FOREIGN KEY (evaluator_id) REFERENCES public.users(id)
);
CREATE TABLE public.inconsistencies (
  id integer NOT NULL DEFAULT nextval('inconsistencies_id_seq'::regclass),
  user_id uuid NOT NULL,
  inconsistency_date date NOT NULL,
  type character varying NOT NULL,
  justification text,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inconsistencies_pkey PRIMARY KEY (id),
  CONSTRAINT inconsistencies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.macroprocesso (
  id integer NOT NULL DEFAULT nextval('macroprocesso_id_seq'::regclass),
  nome text NOT NULL UNIQUE,
  status USER-DEFINED NOT NULL DEFAULT 'ativo'::atividade_status,
  CONSTRAINT macroprocesso_pkey PRIMARY KEY (id)
);
CREATE TABLE public.processo (
  id integer NOT NULL DEFAULT nextval('processo_id_seq'::regclass),
  nome text NOT NULL,
  macroprocesso_id integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ativo'::atividade_status,
  CONSTRAINT processo_pkey PRIMARY KEY (id),
  CONSTRAINT processo_macroprocesso_id_fkey FOREIGN KEY (macroprocesso_id) REFERENCES public.macroprocesso(id)
);
CREATE TABLE public.projects (
  id integer NOT NULL DEFAULT nextval('projects_id_seq'::regclass),
  name character varying NOT NULL,
  code character varying UNIQUE,
  estimated_hours integer,
  description text,
  department_id integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ativo'::projct_status,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.soft_skills_assessment (
  id integer NOT NULL DEFAULT nextval('soft_skills_assessment_id_seq'::regclass),
  colaborador_id uuid NOT NULL,
  evaluator_id uuid NOT NULL,
  comunicacao text NOT NULL,
  comunicacao_meta text,
  comunicacao_comment text,
  trabalho_em_equipe text NOT NULL,
  trabalho_em_equipe_meta text,
  trabalho_em_equipe_comment text,
  proatividade text NOT NULL,
  proatividade_meta text,
  proatividade_comment text,
  resolucao_de_problemas text NOT NULL,
  resolucao_de_problemas_meta text,
  resolucao_de_problemas_comment text,
  organizacao_de_tempo text NOT NULL,
  organizacao_de_tempo_meta text,
  organizacao_de_tempo_comment text,
  pensamento_critico text NOT NULL,
  pensamento_critico_meta text,
  pensamento_critico_comment text,
  capricho text NOT NULL,
  capricho_meta text,
  capricho_comment text,
  encarar_desafios text NOT NULL,
  encarar_desafios_meta text,
  encarar_desafios_comment text,
  postura_profissional text NOT NULL,
  postura_profissional_meta text,
  postura_profissional_comment text,
  gentileza_e_educacao text NOT NULL,
  gentileza_e_educacao_meta text,
  gentileza_e_educacao_comment text,
  engajamento_missao_visao text NOT NULL,
  engajamento_missao_visao_meta text,
  engajamento_missao_visao_comment text,
  created_at date DEFAULT CURRENT_DATE,
  semestre USER-DEFINED,
  CONSTRAINT soft_skills_assessment_pkey PRIMARY KEY (id),
  CONSTRAINT fk_softskills_colaborador FOREIGN KEY (colaborador_id) REFERENCES public.users(id),
  CONSTRAINT fk_softskills_evaluator FOREIGN KEY (evaluator_id) REFERENCES public.users(id)
);
CREATE TABLE public.sub_processo (
  id integer NOT NULL DEFAULT nextval('sub_processo_id_seq'::regclass),
  nome text NOT NULL,
  processo_id integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ativo'::atividade_status,
  CONSTRAINT sub_processo_pkey PRIMARY KEY (id),
  CONSTRAINT sub_processo_processo_id_fkey FOREIGN KEY (processo_id) REFERENCES public.processo(id)
);
CREATE TABLE public.time_allocations (
  id integer NOT NULL DEFAULT nextval('time_allocations_id_seq'::regclass),
  user_id uuid NOT NULL,
  project_id integer NOT NULL,
  activity_id integer NOT NULL,
  allocation_date date NOT NULL,
  hours numeric NOT NULL,
  comment text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT time_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT time_allocations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT time_allocations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT time_allocations_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.activities(id)
);
CREATE TABLE public.time_entries (
  user_id uuid NOT NULL,
  entry_date date NOT NULL,
  period smallint NOT NULL CHECK (period = ANY (ARRAY[1, 2, 3])),
  entry_time time without time zone,
  exit_time time without time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT time_entries_pkey PRIMARY KEY (user_id, entry_date, period)
);
CREATE TABLE public.user_departments (
  user_id uuid NOT NULL,
  department_id integer NOT NULL,
  CONSTRAINT user_departments_pkey PRIMARY KEY (user_id, department_id),
  CONSTRAINT user_departments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_departments_department_id_fkey FOREIGN KEY (department_id) REFERENCES public.departments(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  nome character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  role USER-DEFINED NOT NULL DEFAULT 'COLABORADOR'::user_role,
  cargo_id integer,
  status character varying NOT NULL DEFAULT 'active'::character varying,
  working_hours_per_day integer NOT NULL DEFAULT 8,
  banco_horas_anterior numeric NOT NULL DEFAULT 0,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_cargo_id_fkey FOREIGN KEY (cargo_id) REFERENCES public.cargos(id)
);